spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:h2-db;MODE=PostgreSQL;DB_CLOSE_DELAY=-1;NON_KEYWORDS=KEY;
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2